### ISSUE TITLE
[1.19.2] Duping Collar Tags Bug

### ISSUE THREAD

**Issue by chasr34** [AlexModGuy/DomesticationInnovation#160] opened 2023-10-03 21:13 UTC
I got no clue how I am able to do this, but I am able to duplicate the enchanted collar tag I had put on my wolf (as shown on the attached video), this seems extremely abusable and probably should be fixed soon

quick edit: it also seems if I click fast enough, I also get some regular tags back

https://github.com/AlexModGuy/DomesticationInnovation/assets/94485372/07e0fc01-6e9c-4c6f-b79a-e599c33654cb

**Comment by mosharky** [comment] 2023-10-20 20:03
Getting this on 1.20 as well

**Comment by whidte** [comment] 2023-10-23 14:20
It's Healing Aura's problem.This bug can be reproduced.The presence of Healing Aura enchantment will cause this result.

**Comment by DoctorWafflePhD** [comment] 2023-10-24 01:27
Can confirm this is still an issue on the latest 1.20 version. It was supposedly fixed in #104 though Healing Aura still has this problem.

**Comment by mc-goodch** [comment] 2023-10-26 16:09
This is a duplicate of #144

**Closed** 2023-11-29 17:54 UTC
